import "./globals.css";
import Layout from "@/components/shared/Layout";

export const metadata = {
  title: "EchoGPT-AI Chatbox",
  description: "Generated by EchoGPT App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-full min-h-screen">
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
